# configuration File for the tarxiv system.

# hosting information
host: localhost
port: 9000

# database information
sql_db: 
  host: localhost
  port: 3306
  user: tarxiv_user
  pass: pass1234

doc-db:
  host: localhost
  port: 5044
  user: tarxiv_user
  pass: pass1234
  cert: /etc/certs/key.crt
  
# publishing information

