# configuration File for the tarxiv system.

# hosting information
host: localhost
port: 9000

# database information
database:
  host: localhost
  user: tarxiv_user
  pass: pass1234
  
# tns certifications
tns:
  id: 191311
  type: "bot"
  name: "tarxiv"
  site: "https://www.wis-tns.org"
  api_key: "API-KEY-HERE"
  
